src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),
    path("", include("common.core.urls")),
    path("userauths/", include("common.userauths.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/common/userauths/urls.py
from django.urls import path

from common.userauths import views

app_name = "userauths"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_page, name="logout"),
    path("check/", views.check_username_availability, name="check"),
]

src/common/userauths/models.py
import os

import shortuuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.utils.safestring import mark_safe
from PIL import Image
from shortuuid.django_fields import ShortUUIDField


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/username_<id>/filename
    filename = os.path.basename(filename)
    return f"{instance.full_name}_{instance.id}/{filename}"


class User(AbstractUser):
    id = ShortUUIDField(
        primary_key=True,
        editable=False,
        length=5,
        max_length=15,
        alphabet="abcdefghijklmnopqrstuvwxyz",
    )
    email = models.EmailField(max_length=255, unique=True)
    full_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["full_name", "username"]

    def __str__(self):
        return self.username


class Profile(models.Model):
    id = ShortUUIDField(primary_key=True, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    bio = models.TextField(max_length=1000, null=True, blank=True)

    profile_image = models.ImageField(
        null=True,
        blank=True,
        upload_to=user_directory_path,
        default="images/profiles/default.jpg",
    )

    def thumbnail(self):
        return mark_safe(
            '<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 5px;" />'
            % (self.profile_image)
        )

    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(
            user=instance,
            id=instance.id,
            full_name=instance.full_name,
            email=instance.email,
        )


def save_user_profile(sender, instance, *args, **kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

src/common/userauths/forms.py
from typing import Any

from crispy_bootstrap5.bootstrap5 import FloatingField
from django import forms
from django.contrib.auth.forms import UserCreationForm

from common.userauths.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "full_name", "username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        for fieldname in ["password1", "password2"]:
            self.fields[fieldname].help_text = None
        self.fields["username"].label = "Username (lower case only and no spaces)"
        self.fields["password1"].label = "Password"
        self.fields["password2"].label = "Re-enter Password"

        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

    # This is an interal Django function and we are overwriting it (esplanation: https://github.com/pennersr/django-allauth/blob/4bb9e0170f37d8196bd0c4a78e83adb7b779c113/allauth/account/adapter.py#L175)
    def clean_email(self):
        email = self.cleaned_data.get("email")

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already taken")

        if len(email) > 255 or len(email) < 5:
            raise forms.ValidationError("Email is invalid")

        return email

src/common/userauths/views.py
import re

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render

from common.userauths.forms import CreateUserForm
from common.userauths.models import User


# Checks if the password is valid.
def password_check(password):
    """Takes one argument (str) password. Returns true if password contains at least 8 characteres with upper case,
    lower case, alpha-numeric, and special characters"""

    length_error = len(password) < 8
    digit_error = re.search(r"\d", password) is None
    uppercase_error = re.search(r"[A-Z]", password) is None
    lowercase_error = re.search(r"[a-z]", password) is None
    symbol_error = re.search(r"\W", password) is None
    password_ok = not (
        length_error
        or digit_error
        or uppercase_error
        or lowercase_error
        or symbol_error
    )

    if password_ok:
        return True
    else:
        return False


# Using this method you have control over the messages and creating the contexts.
def register(request):

    if request.method == "POST":
        email = request.POST.get("email").strip()
        username = request.POST.get("username").strip().lower().replace(" ", "")
        full_name = request.POST.get("full_name").strip()
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        email_exists = User.objects.filter(email=email).exists()
        username_exists = User.objects.filter(username=username).exists()

        context = {
            "usrename": username,
            "email": email,
            "full_name": full_name,
        }

        if len(email) < 5 or len(email) > 254:
            messages.error(request, "Email must be valid")
            context["email"] = ""
            return render(request, "userauths/register.html", context)

        elif email_exists:
            messages.error(request, "Email is already taken")
            context["email"] = ""
            return render(request, "userauths/register.html", context)

        elif len(username) < 4:
            messages.error(request, "Username must be at least 4 characters")
            context["username"] = ""
            return render(request, "userauths/register.html", context)

        elif username_exists:
            messages.error(request, "Username is already taken")
            context["username"] = ""
            return render(request, "userauths/register.html", context)

        elif password1 != password2:
            messages.error(request, "Passwords do not match")
            return render(request, "userauths/register.html", context)

        elif not password_check(password1):
            messages.error(
                request,
                "Password must contain at least 8 characters with upper case, lower case, alpha-numeric, and special characters",
            )
            return render(request, "userauths/register.html", context)

        else:

            User.objects.create_user(
                username=username, email=email, full_name=full_name, password=password1
            )
            return HttpResponse("Account created successfully")

    return render(
        request,
        "userauths/register.html",
    )


# There are two ways to do this. If you use the built in form then you do not have control over the messages and creating the contexts.


def login_page(request):

    if request.method == "POST":
        email = request.POST.get("email").strip()
        password = request.POST.get("password")

        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("core:home")
        else:
            messages.error(request, "Invalid username or password")

    return render(request, "userauths/login.html")


def logout_page(request):
    logout(request)
    return redirect("userauths:login")


def check_username_availability(request):
    username = request.GET.get("username")
    username = username.strip().lower()
    available = not User.objects.filter(username=username).exists()

    if len(username) < 4 or " " in username:
        return JsonResponse({"success": False}, status=200)
    if available:
        return JsonResponse({"success": True}, status=200)
    else:
        return JsonResponse({"success": False}, status=200)


def register_using_form(request):

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        email = request.POST.get("email")
        username = request.POST.get("username")
        full_name = request.POST.get("full_name")
        password1 = request.POST.get("password1")

        if form.is_valid():
            user = form.save(commit=False)
            user.email = email
            user.username = username
            user.full_name = full_name
            user.set_password(password1)
            print(form.cleaned_data["email"])  # works
            # user.save()
            return HttpResponse("Account created successfully")

        if form.errors:
            for key, value in form.errors.items():
                messages.error(request, value.as_text().replace("*", ""))
                break
            return render(request, "userauths/register.html")

    return render(
        request,
        "userauths/register.html",
    )

src/templates/userauths/login.html
{% extends 'layouts/layout-main.html' %}

<!-- prettier-ignore -->
{% block title %}
  Login
{% endblock title %}


{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/userauths.css' %}" />
{% endblock css %}

<!-- end prettier-ignore -->

<body>
  <!-- block -->
  {% block content %}
  <!--  -->

  <!-- prettier-ignore -->
  <div class="registerContainer"> 
    <h1 class="heading">Login</h1>
    {% if messages %}
    {% for message in messages|slice:"1" %}
    <div class="alert alert-warning" role="alert">
      {{ message }}
    </div>
    {% endfor %}
      
    {% endif %}

  <form id="inputForm" method="POST">
    {% csrf_token %}
    <div class="form-floating mb-3 mt-3">
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email"  required value="{{email}}">
      <label for="email">Email</label>
    </div>
    <div class="form-floating mb-3 mt-3">
      <input type="password" class="form-control" id="password" placeholder="Enter password" name="password" required />
      <label for="password">Please enter password</label>
    </div>
      <br>
      <button type="submit" class="btn btn-secondary btn-large w-100 btn-block p-2">&nbsp; Login</button>
    </div>
  </form>
  <br>
  <p><a href="{% url 'userauths:register' %}">Need and account? Click here</a></p>
  </div>
  <!-- end prettier-ignore -->
  {% endblock content %}
</body>

<!-- prettier-ignore -->
{% block js %}
{% load static %}
<script src="{% static 'JS/userauths.js' %}"></script>
{% endblock js %}
<!-- end prettier-ignore -->

src/templates/userauths/register.html
{% extends 'layouts/layout-main.html' %}

<!-- prettier-ignore -->
{% block title %}
  Register
{% endblock title %}


{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/userauths.css' %}" />
{% endblock css %}

<!-- end prettier-ignore -->

<body>
  <!-- block -->
  {% block content %}
  <!--  -->

  <!-- prettier-ignore -->
  <div class="registerContainer"> 
    <h1 class="heading">Register</h1>
    {% if messages %}
    {% for message in messages|slice:"1" %}
    <div class="alert alert-warning" role="alert">
      {{ message }}
    </div>
    {% endfor %}
      
    {% endif %}

  <form id="inputForm" method="POST">
    {% csrf_token %}
    <div class="form-floating mb-3 mt-3">
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email"  required value="{{email}}">
      <label for="email">Email</label>
    </div>
    <!-- to appear next, add parent div mt-3 d-flex align-items-center, add span class="ms-2" -->
    <!--  -->
    <div class="form-floating mb-3 mt-3 d-flex align-items-center">
      <input type="text" class="form-control" id="username" placeholder="Please choose username (no spaces and lowercase only)" name="username" required value="{{username}}">
      <label for="username">username (no spaces and lowercase only)</label>
      <i id="alertIcon" class=""></i>
    </div>
    <div class="form-floating mb-3 mt-3">
      <input type="text" class="form-control" id="full_name" placeholder="Enter full_name" name="full_name" required value="{{full_name}}" />
      <label for="full_name">Full name</label>
    </div>
    <div class="form-floating mb-3 mt-3">
      <input type="password" class="form-control" id="password1" placeholder="Enter password" name="password1" required />
      <label for="password1">Please enter password</label>
    </div>
    <div class="form-floating mb-3 mt-3">
      <input type="password" class="form-control" id="password2" placeholder="Confrim password" name="password2" required />
      <label for="password2">Please confirm password</label>
      <br>
      <button id="submitButton" disabled type="submit" class="btn btn-secondary btn-large w-100 btn-block p-2">&nbsp; Register</button>
    </div>
  </form>
  <p><a href="{% url 'userauths:login' %}">Already registered? Click here</a></p>
  </div>
  <!-- end prettier-ignore -->
  {% endblock content %}
</body>

<!-- prettier-ignore -->
{% block js %}
{% load static %}
<script src="{% static 'JS/userauths.js' %}"></script>
{% endblock js %}
<!-- end prettier-ignore -->

src/templates/userauths/register_builtin_django.html
{% extends 'layouts/layout-main.html' %}

<body>
  <!-- block -->
  {% block content %}
  <!--  -->
  {% load crispy_forms_tags %}

  <!-- prettier-ignore -->
  <form id="inputForm" action="">
    <h1 class="heading">Register</h1>
      {{form.email|as_crispy_field}}
      {{form.username|as_crispy_field}}
      {{form.full_name|as_crispy_field}}
      {{form.password1|as_crispy_field}}
      {{form.password2|as_crispy_field}}
    </form>
  <!-- end prettier-ignore -->
  {% endblock content %}
</body>

src/templates/userauths/register_builtin_floating.html
{% extends 'layouts/layout-main.html' %}

<body>
  <!-- block -->
  {% block content %}
  <!--  -->
  {% load crispy_forms_tags %}

  <!-- prettier-ignore -->
  <form id="inputForm" action="">
    <h1 class="heading">Register</h1>

    <!-- {{forms|crispy}} -->
      
    <div class="form-floating">
      {{ form.email }}
      {{ form.email.label_tag }}
    </div>
    <br>
    <div class="form-floating">
      {{ form.username }}
      {{ form.username.label_tag }}
    </div>
    <br>
    <div class="form-floating">
      {{ form.full_name }}
      {{ form.full_name.label_tag }}
    </div>
    <br>
    <div class="form-floating">
      {{ form.password1 }}
      {{ form.password1.label_tag }}
    </div>
    <br>
    <div class="form-floating">
      {{ form.password2 }}
      {{ form.password2.label_tag }}
    </div>
    <br>
    </form>
  <!-- end prettier-ignore -->
  {% endblock content %}
</body>